import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import MainProvider from "@/provider/mainProvider";
import { Toaster } from "sonner";
import SideBar from "@/components/sidebar";
import { Sidebar, SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/components/header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}  antialiased`}
        suppressHydrationWarning
      >
        <MainProvider>
          <SidebarProvider suppressHydrationWarning>
            <Sidebar>
              <SideBar />
            </Sidebar>
            <main className="w-full">
              <Header />
              <MainProvider>{children}</MainProvider>
            </main>
          </SidebarProvider>
          <Toaster position="top-center" />
        </MainProvider>
      </body>
    </html>
  );
}
